version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "root"
    ports:
      - "5672:5672" # Puerto estándar de RabbitMQ
      - "15672:15672" # Puerto de la interfaz de administración web
    volumes:
      - "./data:/var/lib/rabbitmq" # Almacena los datos de RabbitMQ aquí
      - "./log:/var/log/rabbitmq" # Almacena los logs de RabbitMQ aquí
